#!/bin/bash

figshare_ID=4763686
version=1

mkdir $figshare_ID
curl -Lk -o ${figshare_ID}.zip \
    https://ndownloader.figshare.com/articles/${figshare_ID}/versions/$version
unzip -d $figshare_ID ${figshare_ID}.zip

mv $figshare_ID/* ./
