name: "Tests"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

defaults:
  run:
    shell: bash -l {0}

jobs:
  intro-tutorial:
    runs-on: ubuntu-latest
    name: "Intro tutorial"
    strategy:
      matrix:
        CONDA_PY:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.CONDA_PY }}
          environment-file: binder/environment.yml
          activate-environment: ops-tutorial
          miniforge-variant: Mambaforge
      - name: "Install testing tools"
        run: python -m pip install pytest nbval
      - name: "Conda info"
        run: |
          conda info
          conda list
      - name: "Patch answers"
        run: source devtools/patch-all
      - name: "Download data"
        run: source devtools/download-files
      - name: "Run tests"
        run: |
          pytest --nbval-lax \
            1_tps_sampling_tutorial.ipynb \
            2_tps_analysis_tutorial.ipynb \
            3_committor_analysis_tutorial.ipynb \
            4_mstis_sampling_tutorial.ipynb

  advanced-tutorial:
    runs-on: ubuntu-latest
    name: "Advanced tutorial"
    strategy:
      matrix:
        CONDA_PY:
          - 3.7
          - 3.8
          - 3.9

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.CONDA_PY }}
          environment-file: binder/environment.yml
          activate-environment: ops-tutorial
          miniforge-variant: Mambaforge
      - name: "Install testing tools"
        run: python -m pip install pytest nbval
      - name: "Conda info"
        run: |
          conda info
          conda list
      - name: "Patch answers"
        run: source devtools/patch-all
      - name: "Run tests"
        run: |
          pytest --nbval-lax 5_custom_shooting_setup.ipynb
          source devtools/run5.sh
          pytest --nbval-lax \
            6_custom_shooting_analysis.ipynb \
            7_parallel_tis_setup.ipynb
          source devtools/run7.sh
          pytest --nbval-lax 8_parallel_tis_analysis.ipynb

